### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [pyrech/PixelDraw-Server#1]
This app seems to be missing a LICENSE.md file. I suggest AGPLv3 :)

**Comment by rvion** [comment]
https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by pyrech** [comment]
Please @pizzamaker, stop your stupid bot to **spam** all repositories without a licence file.

As you can read in its description, PixelDraw is a school project, whose last commit is 3 years old. This project is in no way mean to be reused, nor maintained and I really doubt that you will find some code interesting to reuse. So no, there is no need to add a license file, please considered this project as proprietary. Thanks for your comprehension.

**Comment by florianmski** [comment]
![](http://i.imgur.com/ueT0WB5.gif)

**Comment by pizzamaker** [comment]
It's not a bot, I simply try to remind developers when they forget their licenses, because they're important.
